export type Recipe = {
  id: string;
  name: string;
  category: "cafe" | "almoco" | "jantar" | "lanche" | "pretreino" | "postreino" | "shake";
  goal: ("bulk" | "cut" | "maintain")[];
  time_min: number;
  servings: number;
  kcal: number; protein: number; carbs: number; fat: number;
  ingredients: string[];
  steps: string[];
  tip?: string;
};

const r = (
  id: string, name: string, category: Recipe["category"], goal: Recipe["goal"],
  time_min: number, kcal: number, protein: number, carbs: number, fat: number,
  ingredients: string[], steps: string[], tip?: string,
): Recipe => ({ id, name, category, goal, time_min, servings: 1, kcal, protein, carbs, fat, ingredients, steps, tip });

export const RECIPES: Recipe[] = [
  // Café da manhã (10)
  r("c1","Panqueca proteica de banana","cafe",["bulk","maintain"],10,420,32,52,9,
    ["1 banana madura","2 ovos","40g aveia em flocos","1 scoop whey baunilha","Canela a gosto"],
    ["Bata todos os ingredientes no liquidificador","Aqueça frigideira antiaderente","Despeje porções e doure 2 min de cada lado","Sirva com mel ou frutas vermelhas"],
    "Use frigideira pequena para panquecas mais fofas."),
  r("c2","Omelete fit de espinafre","cafe",["cut","maintain"],8,310,28,6,18,
    ["3 claras + 1 ovo inteiro","1 punhado de espinafre","30g queijo cottage","Sal, pimenta, azeite"],
    ["Refogue o espinafre rapidamente no azeite","Adicione os ovos batidos com sal e pimenta","Cozinhe em fogo baixo até firmar","Finalize com cottage por cima"]),
  r("c3","Tapioca recheada com frango","cafe",["bulk","maintain"],12,380,30,42,8,
    ["3 colheres goma de tapioca","80g frango desfiado","1 fatia muçarela light","Tomate em cubos","Orégano"],
    ["Espalhe a goma em frigideira quente","Vire quando soltar","Recheie com frango e queijo","Dobre e sirva quente"]),
  r("c4","Iogurte parfait fitness","cafe",["cut","maintain"],5,290,24,32,5,
    ["200g iogurte grego natural","1 scoop whey","30g granola","Frutas vermelhas","Mel"],
    ["Misture o whey ao iogurte","Monte em camadas com granola e frutas","Finalize com fio de mel"]),
  r("c5","Crepioca de aveia","cafe",["bulk"],10,460,36,48,12,
    ["1 ovo + 2 claras","30g aveia","20g goma de tapioca","60g peito de peru","1 fatia queijo branco"],
    ["Bata ovo, claras, aveia e tapioca","Despeje em frigideira","Recheie com peru e queijo","Sirva fechado"]),
  r("c6","Smoothie verde detox","cafe",["cut"],5,240,22,24,4,
    ["200ml leite de amêndoas","1 scoop whey","1 punhado espinafre","1/2 banana","1 col. chá de chia"],
    ["Bata tudo no liquidificador por 1 min","Sirva imediatamente bem gelado"]),
  r("c7","Aveia overnight de cacau","cafe",["bulk","maintain"],5,410,24,58,10,
    ["50g aveia","250ml leite desnatado","1 col. cacau 100%","1 col. pasta de amendoim","1 banana fatiada"],
    ["Misture aveia, leite e cacau num pote","Leve à geladeira por 6h ou overnight","Cubra com banana e pasta de amendoim"]),
  r("c8","Wrap integral de ovo e abacate","cafe",["maintain"],10,440,26,38,18,
    ["1 wrap integral","2 ovos","1/2 abacate","Folhas verdes","Limão e sal"],
    ["Bata os ovos e faça omelete","Amasse o abacate com limão e sal","Monte o wrap com tudo e enrole"]),
  r("c9","Mingau proteico de aveia","cafe",["bulk"],8,520,32,68,10,
    ["60g aveia","300ml leite","1 scoop whey chocolate","1 col. mel","Canela"],
    ["Cozinhe a aveia no leite até cremoso","Tire do fogo e misture o whey","Finalize com mel e canela"]),
  r("c10","Pão de queijo de frigideira","cafe",["cut","maintain"],8,260,18,22,10,
    ["1 ovo","2 col. polvilho doce","30g queijo minas ralado","Sal"],
    ["Misture tudo até virar massa","Faça pequenas porções na frigideira","Doure em fogo baixo dos dois lados"]),

  // Almoço (12)
  r("a1","Frango grelhado com batata-doce","almoco",["bulk","cut","maintain"],25,560,52,52,14,
    ["180g peito de frango","200g batata-doce","Brócolis no vapor","Azeite, alho, sal, pimenta"],
    ["Tempere o frango com alho, sal e pimenta","Grelhe 6 min de cada lado","Asse a batata-doce em rodelas com azeite","Sirva com brócolis no vapor"]),
  r("a2","Strogonoff fit de frango","almoco",["maintain"],25,520,48,38,16,
    ["180g frango em cubos","100g cogumelos","100g iogurte grego","2 col. extrato tomate","100g arroz integral"],
    ["Doure o frango com cebola","Adicione cogumelos e extrato de tomate","Desligue o fogo e misture o iogurte grego","Sirva com arroz integral"]),
  r("a3","Salmão com quinoa","almoco",["cut","maintain"],20,580,42,48,22,
    ["150g filé de salmão","80g quinoa","Aspargos","Limão, alho, azeite"],
    ["Tempere o salmão com limão e alho","Grelhe 4 min de cada lado","Cozinhe a quinoa em água com sal","Sirva com aspargos grelhados"]),
  r("a4","Bowl mexicano de frango","almoco",["bulk","maintain"],20,640,48,68,16,
    ["150g frango desfiado","100g arroz","100g feijão preto","1/4 abacate","Tomate, milho, coentro"],
    ["Tempere o frango com cominho e páprica","Monte o bowl com arroz, feijão, frango","Finalize com abacate, tomate e milho"]),
  r("a5","Macarrão integral à bolonhesa","almoco",["bulk"],25,680,42,82,16,
    ["120g macarrão integral","150g patinho moído","Molho de tomate caseiro","Cebola, alho, manjericão"],
    ["Refogue cebola, alho e a carne","Acrescente molho de tomate e cozinhe 10 min","Cozinhe o macarrão al dente","Sirva com manjericão fresco"]),
  r("a6","Tilápia ao limão com legumes","almoco",["cut"],20,380,42,18,14,
    ["180g filé de tilápia","Abobrinha, cenoura, vagem","Limão, alho, azeite, ervas"],
    ["Tempere a tilápia com limão e ervas","Cozinhe na frigideira 3 min/lado","Refogue os legumes em juliana"]),
  r("a7","Carne de panela com purê de couve-flor","almoco",["cut","maintain"],40,500,48,18,24,
    ["180g acém","1 couve-flor","Cebola, alho, louro","Leite desnatado, sal"],
    ["Cozinhe a carne na panela de pressão por 30 min","Cozinhe a couve-flor e bata com leite","Tempere o purê e sirva com a carne"]),
  r("a8","Risoto de frango e brócolis","almoco",["maintain"],30,580,42,68,14,
    ["100g arroz arbóreo","150g frango em cubos","Brócolis","Caldo de legumes","Parmesão"],
    ["Doure o frango e reserve","Refogue o arroz e adicione caldo aos poucos","Acrescente o brócolis e o frango","Finalize com parmesão"]),
  r("a9","Quibe assado de abóbora","almoco",["cut"],35,420,38,32,14,
    ["150g patinho moído","200g abóbora cozida","30g trigo para quibe","Hortelã, cebola, sal"],
    ["Misture todos os ingredientes","Modele em forma untada","Asse 25 min a 200°C"]),
  r("a10","Lasanha de berinjela proteica","almoco",["cut","maintain"],45,460,42,22,22,
    ["1 berinjela","150g patinho moído","Molho de tomate","Queijo branco light","Manjericão"],
    ["Grelhe fatias de berinjela","Refogue a carne com o molho","Monte camadas alternadas com queijo","Asse 25 min a 180°C"]),
  r("a11","Frango xadrez fit","almoco",["maintain"],20,510,46,38,14,
    ["180g frango em cubos","Pimentões coloridos","Castanha de caju","Shoyu light, gengibre","80g arroz"],
    ["Doure o frango com gengibre","Adicione pimentões e shoyu","Finalize com castanhas e sirva com arroz"]),
  r("a12","Hambúrguer caseiro com salada","almoco",["bulk","maintain"],20,580,42,42,22,
    ["150g patinho moído","1 pão integral","Alface, tomate, cebola roxa","Mostarda, iogurte grego"],
    ["Modele o hambúrguer e tempere","Grelhe 4 min de cada lado","Monte o pão com a salada e molho de iogurte"]),

  // Jantar (10)
  r("j1","Sopa cremosa de abóbora e frango","jantar",["cut","maintain"],25,360,32,28,10,
    ["300g abóbora","120g frango desfiado","Cebola, alho, gengibre","Caldo caseiro"],
    ["Cozinhe a abóbora com cebola e alho","Bata até cremoso","Volte ao fogo com o frango desfiado","Sirva quente com gengibre ralado"]),
  r("j2","Wrap de atum","jantar",["cut"],10,380,36,28,12,
    ["1 wrap integral","1 lata atum em água","Iogurte grego","Cenoura ralada, alface","Pepino"],
    ["Misture o atum com iogurte grego","Recheie o wrap com vegetais e atum","Enrole e sirva"]),
  r("j3","Frango desfiado com purê de mandioquinha","jantar",["bulk","maintain"],30,540,46,52,14,
    ["180g frango cozido desfiado","250g mandioquinha","Leite, sal, noz-moscada","Cebolinha"],
    ["Cozinhe e amasse a mandioquinha com leite","Tempere o frango desfiado","Monte o prato e finalize com cebolinha"]),
  r("j4","Salada caesar de frango","jantar",["cut"],15,440,42,18,22,
    ["150g frango grelhado em tiras","Alface americana","Croutons integrais","Parmesão","Iogurte, mostarda, limão"],
    ["Misture iogurte, mostarda e limão para o molho","Monte a salada com alface, croutons e frango","Finalize com parmesão e o molho"]),
  r("j5","Omelete recheado com frango","jantar",["cut","maintain"],12,420,42,8,22,
    ["3 claras + 1 ovo","100g frango desfiado","Tomate em cubos","Cheiro-verde"],
    ["Bata os ovos e tempere","Faça o omelete em fogo baixo","Recheie com frango e tomate","Dobre e sirva"]),
  r("j6","Filé de peixe com legumes assados","jantar",["cut","maintain"],25,400,38,22,16,
    ["180g pescada","Abobrinha, pimentão, cebola","Azeite, limão, alecrim"],
    ["Tempere o peixe com limão e alecrim","Disponha com legumes em assadeira","Asse 20 min a 200°C"]),
  r("j7","Crepe proteico de espinafre","jantar",["maintain"],15,420,32,38,14,
    ["2 ovos","30g aveia","Espinafre","100g ricota","Tomate seco"],
    ["Bata ovos, aveia e espinafre","Faça crepes finos na frigideira","Recheie com ricota e tomate seco"]),
  r("j8","Hambúrguer de grão-de-bico","jantar",["cut","maintain"],25,380,22,42,12,
    ["200g grão-de-bico cozido","Cebola, alho, salsinha","30g aveia","1 ovo","Páprica defumada"],
    ["Bata todos os ingredientes no processador","Modele hambúrgueres","Doure 4 min de cada lado em frigideira antiaderente"]),
  r("j9","Pizza de frigideira fit","jantar",["maintain"],15,460,32,42,16,
    ["2 ovos","30g aveia","Molho de tomate","100g frango desfiado","Queijo branco, orégano"],
    ["Bata ovos com aveia e cozinhe na frigideira","Vire e cubra com molho, frango e queijo","Tampe até derreter o queijo"]),
  r("j10","Salada power com salmão","jantar",["cut"],15,520,36,18,32,
    ["120g salmão grelhado","Mix de folhas","1/2 abacate","Tomate cereja","Sementes de gergelim"],
    ["Grelhe o salmão temperado","Monte a salada","Finalize com abacate, tomate, gergelim e azeite"]),

  // Lanches (8)
  r("l1","Mix de oleaginosas","lanche",["bulk","maintain"],2,260,8,12,22,
    ["20g castanha-do-pará","20g amêndoas","20g nozes","Uvas-passas a gosto"],
    ["Misture tudo em um pote hermético","Porcione 30g por dia"]),
  r("l2","Sanduíche natural","lanche",["maintain"],10,360,28,32,12,
    ["2 fatias pão integral","80g peito de frango desfiado","Iogurte grego, mostarda","Alface, tomate, cenoura"],
    ["Misture frango com iogurte e mostarda","Monte o sanduíche com vegetais"]),
  r("l3","Ovos cozidos com cottage","lanche",["cut"],12,260,28,4,14,
    ["3 ovos cozidos","100g queijo cottage","Pimenta-do-reino, ervas"],
    ["Cozinhe os ovos por 9 min","Sirva com cottage temperado"]),
  r("l4","Pasta de atum com torradas","lanche",["cut","maintain"],8,320,34,22,10,
    ["1 lata atum em água","2 col. iogurte grego","Cebolinha","3 torradas integrais"],
    ["Misture atum, iogurte e cebolinha","Sirva sobre as torradas"]),
  r("l5","Iogurte com frutas e granola","lanche",["maintain"],3,290,18,38,6,
    ["200g iogurte natural","1 fruta picada","30g granola sem açúcar","Mel"],
    ["Monte em camadas em um copo","Finalize com mel"]),
  r("l6","Pasta de amendoim com banana","lanche",["bulk"],3,340,12,42,16,
    ["1 banana","2 col. pasta de amendoim integral","Canela"],
    ["Corte a banana em rodelas","Espalhe pasta e finalize com canela"]),
  r("l7","Bolinho de aipim com frango","lanche",["maintain"],25,360,28,38,10,
    ["200g aipim cozido","100g frango desfiado","1 ovo","Cheiro-verde"],
    ["Misture todos os ingredientes","Modele bolinhos","Asse 20 min a 200°C"]),
  r("l8","Chips de batata-doce","lanche",["maintain"],30,240,4,42,6,
    ["1 batata-doce","Azeite, sal, páprica"],
    ["Fatie bem fino","Tempere e asse 25 min a 200°C virando na metade"]),

  // Pré-treino (6)
  r("p1","Banana com aveia e mel","pretreino",["bulk","maintain"],3,280,6,58,4,
    ["1 banana","30g aveia","1 col. mel","Canela"],
    ["Misture tudo em um pote","Consuma 45 min antes do treino"]),
  r("p2","Tapioca com geleia 100% fruta","pretreino",["bulk","cut","maintain"],8,260,4,52,2,
    ["3 col. goma de tapioca","2 col. geleia 100% fruta"],
    ["Faça a tapioca","Recheie com geleia e dobre"]),
  r("p3","Smoothie energético","pretreino",["bulk"],5,360,18,58,6,
    ["1 banana","200ml leite","30g aveia","1 col. cacau","1 tâmara"],
    ["Bata tudo no liquidificador","Tome 30 min antes do treino"]),
  r("p4","Pão integral com geleia","pretreino",["maintain"],3,240,8,42,4,
    ["2 fatias pão integral","2 col. geleia 100% fruta"],
    ["Monte sanduíche","Consuma 40 min antes"]),
  r("p5","Café com pasta de amendoim","pretreino",["cut"],5,180,6,8,14,
    ["1 xícara café","1 col. pasta de amendoim","Canela"],
    ["Misture café com pasta","Tome morno antes do treino"]),
  r("p6","Mingau rápido pré-treino","pretreino",["bulk"],8,320,10,58,6,
    ["40g aveia","250ml leite","1 col. mel"],
    ["Cozinhe aveia no leite","Adoce com mel e sirva morno"]),

  // Pós-treino (6)
  r("o1","Shake recovery clássico","postreino",["bulk","cut","maintain"],3,300,32,32,4,
    ["1 scoop whey","1 banana","250ml água ou leite","Gelo"],
    ["Bata tudo no shaker","Tome até 30 min após o treino"]),
  r("o2","Wrap de frango pós-treino","postreino",["bulk","maintain"],10,460,38,42,12,
    ["1 wrap integral","120g frango desfiado","Cenoura, alface","Iogurte grego"],
    ["Recheie o wrap","Enrole e leve para o pós-treino"]),
  r("o3","Bowl de açaí proteico","postreino",["bulk"],8,520,28,72,12,
    ["200g polpa de açaí","1 scoop whey","1 banana","Granola, mel"],
    ["Bata açaí, banana e whey","Cubra com granola e mel"]),
  r("o4","Omelete com batata-doce","postreino",["maintain"],15,440,32,38,16,
    ["3 ovos","150g batata-doce","Espinafre","Sal e pimenta"],
    ["Cozinhe e amasse a batata-doce","Misture aos ovos batidos","Faça o omelete e sirva"]),
  r("o5","Sanduíche de atum integral","postreino",["cut"],8,380,36,32,10,
    ["2 fatias pão integral","1 lata atum","Iogurte, alface","Tomate"],
    ["Misture atum com iogurte","Monte o sanduíche"]),
  r("o6","Arroz com frango pós-treino","postreino",["bulk"],20,560,42,68,10,
    ["100g arroz","150g frango desfiado","Cenoura, ervilha","Cheiro-verde"],
    ["Refogue legumes e frango","Misture com arroz cozido"]),

  // Shakes (8)
  r("s1","Shake chocolate amendoim","shake",["bulk"],3,420,32,38,16,
    ["1 scoop whey chocolate","250ml leite","1 banana","1 col. pasta de amendoim"],
    ["Bata tudo no liquidificador","Sirva com gelo"]),
  r("s2","Shake morango cheesecake","shake",["maintain"],3,310,28,28,8,
    ["1 scoop whey baunilha","200g iogurte grego","100g morangos","Adoçante"],
    ["Bata até cremoso","Sirva imediatamente"]),
  r("s3","Shake verde antioxidante","shake",["cut"],4,260,26,18,6,
    ["1 scoop whey","Espinafre","1/2 abacaxi","Gengibre","Água de coco"],
    ["Bata tudo até homogêneo","Sirva bem gelado"]),
  r("s4","Shake banoffee","shake",["bulk"],3,440,30,52,10,
    ["1 scoop whey baunilha","1 banana","250ml leite","1 tâmara","Canela"],
    ["Bata todos os ingredientes","Polvilhe canela"]),
  r("s5","Shake café cremoso","shake",["maintain"],4,300,28,18,12,
    ["1 scoop whey baunilha","1 dose café espresso","200ml leite","Gelo"],
    ["Bata todos os ingredientes","Sirva em copo alto"]),
  r("s6","Shake tropical","shake",["cut","maintain"],4,290,26,32,4,
    ["1 scoop whey","100g manga","100g abacaxi","Hortelã"],
    ["Bata tudo com gelo","Decore com hortelã"]),
  r("s7","Shake high carb pré-treino","shake",["bulk"],4,460,30,58,10,
    ["1 scoop whey","1 banana","30g aveia","1 col. mel","Leite"],
    ["Bata tudo bem","Tome 40 min antes do treino"]),
  r("s8","Shake low carb noturno","shake",["cut"],3,220,30,8,8,
    ["1 scoop caseína ou whey","200ml leite desnatado","Canela"],
    ["Bata e sirva à noite","Saciedade prolongada"]),
];

export const CATEGORY_LABEL: Record<Recipe["category"], string> = {
  cafe: "Café da manhã",
  almoco: "Almoço",
  jantar: "Jantar",
  lanche: "Lanches",
  pretreino: "Pré-treino",
  postreino: "Pós-treino",
  shake: "Shakes",
};
