export type Recipe = {
  id: string;
  name: string;
  emoji: string;
  category: "cafe" | "almoco" | "jantar" | "lanche" | "pretreino" | "postreino" | "shake";
  goal: ("bulk" | "cut" | "maintain")[];
  time_min: number;
  servings: number;
  kcal: number; protein: number; carbs: number; fat: number;
  ingredients: string[];
  steps: string[];
  tip?: string;
};

const r = (
  id: string, name: string, emoji: string, category: Recipe["category"], goal: Recipe["goal"],
  time_min: number, kcal: number, protein: number, carbs: number, fat: number,
  ingredients: string[], steps: string[], tip?: string,
): Recipe => ({ id, name, emoji, category, goal, time_min, servings: 1, kcal, protein, carbs, fat, ingredients, steps, tip });

export const RECIPES: Recipe[] = [
  /* ── CAFÉ DA MANHÃ (14) ── */
  r("c1","Panqueca proteica de banana","🥞","cafe",["bulk","maintain"],10,420,32,52,9,
    ["1 banana madura","2 ovos","40g aveia em flocos","1 scoop whey baunilha","Canela a gosto"],
    ["Bata todos os ingredientes no liquidificador","Aqueça frigideira antiaderente em fogo médio","Despeje porções e doure 2 min de cada lado","Sirva com mel ou frutas vermelhas"],
    "Use frigideira pequena para panquecas mais fofas e uniformes."),
  r("c2","Omelete fit de espinafre","🍳","cafe",["cut","maintain"],8,310,28,6,18,
    ["3 claras + 1 ovo inteiro","1 punhado de espinafre","30g queijo cottage","Sal, pimenta, azeite"],
    ["Refogue o espinafre rapidamente no azeite","Adicione os ovos batidos com sal e pimenta","Cozinhe em fogo baixo até firmar","Finalize com cottage por cima"],
    "Não mexa depois de colocar os ovos — deixe firmar naturalmente."),
  r("c3","Tapioca recheada com frango","🫓","cafe",["bulk","maintain"],12,380,30,42,8,
    ["3 col. goma de tapioca","80g frango desfiado","1 fatia muçarela light","Tomate em cubos","Orégano"],
    ["Espalhe a goma em frigideira quente até soltar","Vire com cuidado","Recheie com frango, queijo e tomate","Dobre e sirva quente"]),
  r("c4","Iogurte parfait fitness","🥣","cafe",["cut","maintain"],5,290,24,32,5,
    ["200g iogurte grego natural","1 scoop whey","30g granola sem açúcar","Frutas vermelhas","Mel"],
    ["Misture o whey ao iogurte até dissolver","Monte em camadas num pote: iogurte, granola, frutas","Finalize com fio de mel"],
    "Prepare de véspera para um café da manhã super rápido."),
  r("c5","Crepioca de aveia","🫔","cafe",["bulk"],10,460,36,48,12,
    ["1 ovo + 2 claras","30g aveia","20g goma de tapioca","60g peito de peru","1 fatia queijo branco"],
    ["Bata ovo, claras, aveia e tapioca","Despeje em frigideira antiaderente","Vire quando soltar","Recheie com peru e queijo e sirva"]),
  r("c6","Smoothie verde detox","🥤","cafe",["cut"],5,240,22,24,4,
    ["200ml leite de amêndoas","1 scoop whey","1 punhado espinafre baby","½ banana congelada","1 col. chá chia"],
    ["Bata tudo no liquidificador por 1 min","Sirva imediatamente bem gelado"],
    "O espinafre não altera o sabor — só deixa verde e nutritivo."),
  r("c7","Aveia overnight de cacau","🌙","cafe",["bulk","maintain"],5,410,24,58,10,
    ["50g aveia","250ml leite desnatado","1 col. cacau 100%","1 col. pasta de amendoim","1 banana fatiada"],
    ["Misture aveia, leite e cacau num pote com tampa","Leve à geladeira overnight","Cubra com banana e pasta de amendoim"],
    "Prep na noite anterior = café da manhã sem estresse."),
  r("c8","Wrap integral de ovo e abacate","🌯","cafe",["maintain"],10,440,26,38,18,
    ["1 wrap integral","2 ovos","½ abacate","Folhas verdes","Limão e sal"],
    ["Faça os ovos mexidos","Amasse o abacate com limão e sal","Monte o wrap com ovos, abacate e folhas e enrole"]),
  r("c9","Mingau proteico de aveia","🍚","cafe",["bulk"],8,520,32,68,10,
    ["60g aveia","300ml leite","1 scoop whey chocolate","1 col. mel","Canela em pó"],
    ["Cozinhe a aveia no leite até cremoso","Tire do fogo e misture o whey (fora do fogo!)","Finalize com mel e canela"],
    "Sempre misture o whey fora do fogo para não desnaturar a proteína."),
  r("c10","Pão de queijo fit","🧀","cafe",["cut","maintain"],8,260,18,22,10,
    ["1 ovo","2 col. polvilho doce","30g queijo minas ralado","Pitada de sal"],
    ["Misture tudo até virar massa homogênea","Faça pequenas porções na frigideira","Doure em fogo baixo dos dois lados"]),
  r("c11","French toast proteico","🍞","cafe",["bulk","maintain"],12,480,34,54,12,
    ["2 fatias pão integral grosso","2 ovos","1 scoop whey baunilha","100ml leite","Canela e baunilha"],
    ["Bata ovos, leite, whey, canela e baunilha","Mergulhe o pão na mistura por 1 min cada lado","Doure na frigideira com azeite","Sirva com mel ou calda de frutas vermelhas"]),
  r("c12","Cottage com frutas e castanhas","🫐","cafe",["cut"],5,280,26,22,8,
    ["150g queijo cottage","100g frutas vermelhas","20g castanhas picadas","1 col. mel"],
    ["Coloque o cottage numa tigela","Cubra com frutas, castanhas e mel","Sirva imediatamente"]),
  r("c13","Burrito de ovos fit","🌮","cafe",["bulk"],15,520,38,48,16,
    ["1 tortilha integral","3 ovos","50g frango desfiado","30g queijo light","Tomate, cebolinha, pimenta"],
    ["Faça os ovos mexidos com o frango","Recheie a tortilha com tudo","Dobre e doure rapidamente na frigideira"]),
  r("c14","Vitamina de mamão com whey","🧡","cafe",["maintain"],5,320,28,38,6,
    ["200g mamão papaia","1 scoop whey baunilha","200ml leite ou bebida vegetal","Gengibre ralado","Gelo"],
    ["Bata tudo no liquidificador","Sirva imediatamente"],
    "O mamão ajuda na digestão — ótimo depois de um treino pela manhã."),

  /* ── ALMOÇO (16) ── */
  r("a1","Frango grelhado com batata-doce","🍗","almoco",["bulk","cut","maintain"],25,560,52,52,14,
    ["180g peito de frango","200g batata-doce","Brócolis no vapor","Azeite, alho, sal, pimenta"],
    ["Tempere o frango com alho, sal e pimenta","Grelhe 6 min de cada lado","Asse a batata-doce em rodelas com azeite","Sirva com brócolis no vapor"],
    "Tempere o frango de véspera para sabor mais intenso."),
  r("a2","Strogonoff fit de frango","🍲","almoco",["maintain"],25,520,48,38,16,
    ["180g frango em cubos","100g cogumelos paris","100g iogurte grego","2 col. extrato tomate","100g arroz integral"],
    ["Doure o frango com cebola e alho","Adicione cogumelos e extrato de tomate","Desligue o fogo e misture o iogurte grego","Sirva com arroz integral"],
    "Misturar o iogurte fora do fogo garante o molho cremoso sem talhar."),
  r("a3","Salmão com quinoa e aspargos","🐟","almoco",["cut","maintain"],20,580,42,48,22,
    ["150g filé de salmão","80g quinoa","1 maço de aspargos","Limão-siciliano, alho, azeite"],
    ["Tempere o salmão com limão e alho","Grelhe 4 min de cada lado","Cozinhe a quinoa em água salgada","Sirva com aspargos grelhados"]),
  r("a4","Bowl mexicano de frango","🌮","almoco",["bulk","maintain"],20,640,48,68,16,
    ["150g frango desfiado","100g arroz","100g feijão preto","¼ abacate","Tomate, milho, coentro, limão"],
    ["Tempere o frango com cominho e páprica","Monte o bowl na ordem: arroz, feijão, frango","Finalize com abacate, tomate, milho e coentro"]),
  r("a5","Macarrão integral à bolonhesa","🍝","almoco",["bulk"],25,680,42,82,16,
    ["120g macarrão integral","150g patinho moído","Molho de tomate caseiro","Cebola, alho, manjericão"],
    ["Refogue cebola, alho e a carne até dourar","Acrescente molho de tomate e cozinhe 10 min","Cozinhe o macarrão al dente","Sirva com manjericão fresco e parmesão light"]),
  r("a6","Tilápia ao limão com legumes","🐠","almoco",["cut"],20,380,42,18,14,
    ["180g filé de tilápia","Abobrinha, cenoura, vagem","Limão, alho, azeite, ervas frescas"],
    ["Tempere a tilápia com limão e ervas","Cozinhe na frigideira 3 min cada lado","Refogue os legumes em juliana no azeite"]),
  r("a7","Frango xadrez","🍜","almoco",["maintain"],20,510,46,38,14,
    ["180g frango em cubos","Pimentões coloridos","50g castanha de caju","Shoyu light, gengibre","80g arroz"],
    ["Doure o frango com gengibre e alho","Adicione pimentões em cubos e shoyu","Finalize com castanhas torradas","Sirva com arroz"]),
  r("a8","Hambúrguer caseiro com salada","🍔","almoco",["bulk","maintain"],20,580,42,42,22,
    ["150g patinho moído","1 pão integral","Alface, tomate, cebola roxa","Mostarda Dijon, iogurte grego"],
    ["Modele o hambúrguer e tempere com sal e pimenta","Grelhe 4 min de cada lado","Monte o pão com salada e molho de iogurte com mostarda"]),
  r("a9","Carne de panela com purê de couve-flor","🥘","almoco",["cut","maintain"],40,500,48,18,24,
    ["180g acém","½ couve-flor","Cebola, alho, louro, tomilho","Leite desnatado, sal"],
    ["Pressione a carne por 30 min com temperos","Cozinhe a couve-flor e bata com leite","Tempere o purê e sirva com a carne"],
    "O purê de couve-flor tem metade das calorias do purê de batata."),
  r("a10","Risoto de frango e brócolis","🫕","almoco",["maintain"],30,580,42,68,14,
    ["100g arroz arbóreo","150g frango em cubos","Brócolis","Caldo de legumes caseiro","Parmesão light"],
    ["Doure o frango e reserve","Refogue o arroz e adicione caldo aos poucos mexendo sempre","Acrescente o brócolis e o frango nos últimos 3 min","Finalize com parmesão"]),
  r("a11","Quibe assado proteico","🧆","almoco",["cut"],35,420,38,32,14,
    ["150g patinho moído","200g abóbora cozida","30g trigo para quibe","Hortelã, cebola, sal, canela"],
    ["Hidrate o trigo por 15 min","Misture todos os ingredientes","Modele em forma untada com azeite","Asse 25 min a 200°C"]),
  r("a12","Salada mediterrânea de atum","🥗","almoco",["cut","maintain"],10,460,38,28,18,
    ["1 lata atum em água","Grão-de-bico cozido","Pepino, tomate cereja, cebola roxa","Azeitonas pretas","Azeite, limão, orégano"],
    ["Escorra e seque o atum","Monte a salada com todos os ingredientes","Tempere com azeite, limão e orégano"]),
  r("a13","Frango ao curry com leite de coco","🍛","almoco",["maintain","bulk"],25,600,44,46,18,
    ["180g frango em cubos","150ml leite de coco light","1 col. curry","Arroz basmati","Coentro, alho, gengibre"],
    ["Doure o frango com alho e gengibre","Adicione curry e leite de coco","Cozinhe 12 min em fogo médio","Sirva sobre o arroz com coentro"]),
  r("a14","Lasanha de berinjela proteica","🫠","almoco",["cut","maintain"],45,460,42,22,22,
    ["1 berinjela grande","150g patinho moído","Molho de tomate","Queijo branco light","Manjericão"],
    ["Grelhe fatias de berinjela sem sal","Refogue a carne com temperos e molho","Monte camadas: berinjela, carne, queijo","Asse 25 min a 180°C"]),
  r("a15","Wrap de frango defumado","🌯","almoco",["cut","maintain"],10,480,38,42,14,
    ["1 wrap integral grande","100g frango defumado","Requeijão light","Alface, tomate, pepino","Mostarda Dijon"],
    ["Aqueça levemente o wrap","Espalhe requeijão e mostarda","Recheie com frango e vegetais","Enrole bem firme e corte ao meio"]),
  r("a16","Poke bowl fit","🥗","almoco",["cut","maintain"],15,540,40,52,16,
    ["150g atum fresco ou enlatado","100g arroz japonês cozido","Edamame","Pepino, cenoura ralada, abacate","Shoyu light, gergelim, gengibre"],
    ["Cozinhe o arroz e resfrie","Monte o bowl com arroz na base","Disponha os toppings em quadrantes","Tempere com shoyu, gergelim e gengibre"]),

  /* ── JANTAR (14) ── */
  r("j1","Sopa cremosa de abóbora","🎃","jantar",["cut","maintain"],25,360,32,28,10,
    ["300g abóbora","120g frango desfiado","Cebola, alho, gengibre","Caldo caseiro","Noz-moscada"],
    ["Cozinhe a abóbora com cebola e alho","Bata até cremoso com o caldo","Volte ao fogo com o frango desfiado","Finalize com gengibre e noz-moscada"],
    "Adicione coco ralado para uma versão mais exótica."),
  r("j2","Wrap de atum fresco","🌯","jantar",["cut"],10,380,36,28,12,
    ["1 wrap integral","1 lata atum em água","Iogurte grego","Cenoura ralada","Alface, pepino, tomate"],
    ["Misture o atum com iogurte grego","Recheie o wrap com atum e vegetais","Enrole firme e sirva"]),
  r("j3","Frango desfiado com purê de mandioquinha","🥔","jantar",["bulk","maintain"],30,540,46,52,14,
    ["180g frango cozido desfiado","250g mandioquinha","Leite, sal, noz-moscada","Cebolinha verde"],
    ["Cozinhe a mandioquinha até bem macia","Amasse com leite, sal e noz-moscada","Tempere o frango com azeite e limão","Monte o prato e finalize com cebolinha"]),
  r("j4","Salada caesar proteica","🥗","jantar",["cut"],15,440,42,18,22,
    ["150g frango grelhado em tiras","Alface americana","Croutons integrais","Parmesão light","Iogurte, mostarda Dijon, limão, alho"],
    ["Misture iogurte, mostarda, limão e alho para o molho","Monte a salada com alface e croutons","Adicione o frango e parmesão","Regue com o molho"]),
  r("j5","Omelete recheado de frango","🍳","jantar",["cut","maintain"],12,420,42,8,22,
    ["3 claras + 1 ovo","100g frango desfiado temperado","Tomate em cubos","Cheiro-verde","Sal e pimenta"],
    ["Bata os ovos e tempere bem","Faça o omelete em frigideira antiaderente fogo baixo","Recheie com frango e tomate antes de dobrar","Sirva imediatamente"]),
  r("j6","Filé de peixe com legumes assados","🐟","jantar",["cut","maintain"],25,400,38,22,16,
    ["180g pescada ou tilápia","Abobrinha, pimentão, cebola roxa","Azeite, limão, alecrim, tomilho"],
    ["Tempere o peixe com limão e ervas","Disponha com legumes cortados em assadeira","Regue com azeite","Asse 20 min a 200°C"]),
  r("j7","Crepe proteico de espinafre","🫔","jantar",["maintain"],15,420,32,38,14,
    ["2 ovos","30g aveia","Espinafre fresco","100g ricota temperada","Tomate seco em óleo"],
    ["Bata ovos, aveia e espinafre no liquidificador","Faça crepes finos na frigideira","Recheie com ricota e tomate seco","Enrole e sirva"]),
  r("j8","Hambúrguer de grão-de-bico","🧆","jantar",["cut","maintain"],25,380,22,42,12,
    ["200g grão-de-bico cozido","Cebola, alho, salsinha fresca","30g aveia","1 ovo","Páprica defumada, cominho"],
    ["Processe os ingredientes grosseiramente","Modele hambúrgueres compactos","Doure 4 min cada lado em frigideira antiaderente","Sirva com salada verde"]),
  r("j9","Pizza de frigideira fit","🍕","jantar",["maintain"],15,460,32,42,16,
    ["2 ovos","30g aveia","3 col. molho de tomate","100g frango desfiado","Queijo branco, orégano"],
    ["Bata ovos com aveia e cozinhe na frigideira","Vire quando firmar","Cubra com molho, frango e queijo","Tampe até derreter"]),
  r("j10","Salada power com salmão","🐠","jantar",["cut"],15,520,36,18,32,
    ["120g salmão grelhado","Mix de folhas frescas","½ abacate","Tomate cereja","Sementes de gergelim, abóbora"],
    ["Grelhe o salmão temperado com sal e pimenta","Monte a salada base","Disponha o salmão em pedaços","Finalize com abacate, tomate, sementes e azeite"]),
  r("j11","Caldo verde proteico","🥣","jantar",["cut","maintain"],20,380,34,24,12,
    ["120g frango ou linguiça de peru light","200g couve manteiga fatiada fina","2 batatas médias","Alho, cebola, azeite, sal"],
    ["Cozinhe as batatas e amasse grosseiramente","Refogue o frango com alho e cebola","Junte ao caldo e cozinhe 5 min","Adicione a couve e sirva imediatamente"]),
  r("j12","Tofu grelhado com legumes","🫑","jantar",["cut","maintain"],20,360,28,24,14,
    ["200g tofu extra firme","Pimentão, abobrinha, brócolis","Shoyu light, alho, gengibre","Gergelim torrado"],
    ["Corte o tofu em fatias e seque bem","Tempere com shoyu, alho e gengibre","Grelhe até dourar cada lado","Sirva com legumes salteados e gergelim"]),
  r("j13","Frango assado com limão e ervas","🍋","jantar",["bulk","cut","maintain"],30,480,48,8,26,
    ["200g sobrecoxa sem pele","Limão, alho, tomilho, alecrim","Azeite, sal, pimenta do reino"],
    ["Faça cortes no frango e tempere bem","Deixe marinar 20 min com limão e ervas","Asse a 200°C por 25 min virando uma vez"]),
  r("j14","Espaguete de abobrinha ao pesto","🥒","jantar",["cut","maintain"],15,380,28,18,22,
    ["2 abobrinhas grandes","150g frango grelhado","2 col. pesto de manjericão","Tomate cereja","Parmesão light"],
    ["Use espiralizador ou descascador para fazer o espaguete","Salteie a abobrinha 2 min no azeite","Misture com pesto e frango fatiado","Finalize com tomate cereja e parmesão"]),

  /* ── LANCHES (10) ── */
  r("l1","Mix de oleaginosas power","🥜","lanche",["bulk","maintain"],2,260,8,12,22,
    ["20g castanha-do-pará","20g amêndoas","20g nozes","Tâmaras ou uvas-passas a gosto"],
    ["Misture tudo em pote hermético","Porcione 30g por lanche"]),
  r("l2","Sanduíche natural proteico","🥪","lanche",["maintain"],10,360,28,32,12,
    ["2 fatias pão integral","80g frango desfiado","Iogurte grego, mostarda Dijon","Alface, tomate, cenoura ralada"],
    ["Misture frango com iogurte e mostarda","Monte o sanduíche com vegetais","Sirva fresco"]),
  r("l3","Ovos cozidos com cottage","🥚","lanche",["cut"],12,260,28,4,14,
    ["3 ovos cozidos","100g queijo cottage","Pimenta-do-reino, ervas finas"],
    ["Cozinhe os ovos por 9 min em água fervente","Descasque e corte ao meio","Sirva com cottage temperado"]),
  r("l4","Pasta de atum com torradas","🫙","lanche",["cut","maintain"],8,320,34,22,10,
    ["1 lata atum em água","2 col. iogurte grego","Cebolinha, limão","3 torradas integrais"],
    ["Misture atum com iogurte, cebolinha e limão","Sirva sobre as torradas"]),
  r("l5","Iogurte com frutas e granola","🍓","lanche",["maintain"],3,290,18,38,6,
    ["200g iogurte natural grego","1 fruta picada (banana, mamão ou maçã)","30g granola sem açúcar","Mel"],
    ["Monte em camadas num pote","Finalize com mel"]),
  r("l6","Pasta de amendoim com banana","🍌","lanche",["bulk"],3,340,12,42,16,
    ["1 banana madura","2 col. pasta de amendoim integral","Canela em pó"],
    ["Corte a banana em rodelas","Espalhe a pasta em cada fatia","Polvilhe canela e sirva"]),
  r("l7","Bolinho de aipim com frango","🫔","lanche",["maintain"],25,360,28,38,10,
    ["200g aipim cozido","100g frango desfiado","1 ovo","Cheiro-verde, sal"],
    ["Amasse o aipim cozido","Misture com frango, ovo e temperos","Modele bolinhos","Asse 20 min a 200°C"]),
  r("l8","Chips de batata-doce","🍠","lanche",["maintain"],30,240,4,42,6,
    ["1 batata-doce média","Azeite, sal marinho, páprica defumada"],
    ["Fatie bem fino (use mandoline se possível)","Tempere e distribua em assadeira","Asse 25 min a 200°C virando na metade"]),
  r("l9","Queijo cottage com pepino","🥒","lanche",["cut"],5,180,20,8,6,
    ["150g queijo cottage","1 pepino em rodelas","Sal, pimenta, azeite","Folhas de hortelã"],
    ["Tempere o cottage com sal e pimenta","Sirva com rodelas de pepino e hortelã"]),
  r("l10","Creme de abacate com torradas","🥑","lanche",["maintain"],8,320,10,22,22,
    ["1 abacate maduro","Limão, sal, pimenta","3 torradas integrais","Tomate cereja, gergelim"],
    ["Amasse o abacate com limão, sal e pimenta","Espalhe nas torradas","Decore com tomate cereja fatiado e gergelim"]),

  /* ── PRÉ-TREINO (8) ── */
  r("p1","Banana com aveia e mel","🍌","pretreino",["bulk","maintain"],3,280,6,58,4,
    ["1 banana","30g aveia","1 col. mel","Canela em pó"],
    ["Misture a aveia no pote","Cubra com a banana fatiada e mel","Consuma 45 min antes do treino"],
    "Carboidratos de rápida absorção = energia garantida no treino."),
  r("p2","Tapioca com geleia de fruta","🫓","pretreino",["bulk","cut","maintain"],8,260,4,52,2,
    ["3 col. goma de tapioca","2 col. geleia 100% fruta"],
    ["Faça a tapioca em frigideira seca","Recheie com a geleia e dobre","Consuma 30 min antes"]),
  r("p3","Smoothie energético pré-treino","⚡","pretreino",["bulk"],5,360,18,58,6,
    ["1 banana congelada","200ml leite","30g aveia","1 col. cacau","1 tâmara"],
    ["Bata tudo no liquidificador","Tome 30 min antes do treino"]),
  r("p4","Pão integral com geleia","🍞","pretreino",["maintain"],3,240,8,42,4,
    ["2 fatias pão integral","2 col. geleia 100% fruta"],
    ["Monte o sanduíche","Consuma 40 min antes do treino"]),
  r("p5","Café bulletproof fitness","☕","pretreino",["cut"],5,180,6,8,14,
    ["1 xícara café forte","1 col. pasta de amendoim","Canela","Opcional: 1 col. óleo de coco"],
    ["Bata o café com pasta no liquidificador","Tome morno 20 min antes"]),
  r("p6","Mingau rápido pré-treino","🫕","pretreino",["bulk"],8,320,10,58,6,
    ["40g aveia","250ml leite","1 col. mel","Frutas secas"],
    ["Cozinhe a aveia no leite até cremoso","Adoce com mel e adicione frutas secas"]),
  r("p7","Torrada com ricota e mel","🍯","pretreino",["maintain","cut"],5,250,14,32,6,
    ["2 torradas integrais","60g ricota","1 col. mel","Canela"],
    ["Espalhe a ricota nas torradas","Regue com mel e polvilhe canela","Consuma 30 min antes"]),
  r("p8","Maçã com pasta de amendoim","🍎","pretreino",["maintain"],3,260,8,36,12,
    ["1 maçã grande","2 col. pasta de amendoim"],
    ["Corte a maçã em fatias","Sirva com pasta de amendoim para dipping"]),

  /* ── PÓS-TREINO (8) ── */
  r("o1","Shake recovery clássico","💪","postreino",["bulk","cut","maintain"],3,300,32,32,4,
    ["1 scoop whey proteína","1 banana","250ml água ou leite desnatado","Gelo"],
    ["Bata tudo no liquidificador","Tome até 30 min após o treino"],
    "Janela anabólica: proteína + carboidrato nos primeiros 30 min."),
  r("o2","Wrap de frango pós-treino","🌯","postreino",["bulk","maintain"],10,460,38,42,12,
    ["1 wrap integral","120g frango desfiado","Cenoura e beterraba raladas","Iogurte grego"],
    ["Recheie o wrap com frango e vegetais","Acrescente o iogurte como molho","Enrole e leve para o pós-treino"]),
  r("o3","Bowl de açaí proteico","🫐","postreino",["bulk"],8,520,28,72,12,
    ["200g polpa de açaí sem açúcar","1 scoop whey","1 banana","Granola, mel, frutas"],
    ["Bata açaí, banana e whey","Coloque no bowl","Cubra com granola, mel e frutas"]),
  r("o4","Omelete com batata-doce","🍠","postreino",["maintain"],15,440,32,38,16,
    ["3 ovos","150g batata-doce cozida","Espinafre","Sal e pimenta"],
    ["Amasse a batata-doce e misture aos ovos batidos","Faça o omelete na frigideira","Adicione o espinafre e dobre"]),
  r("o5","Sanduíche de atum integral","🥪","postreino",["cut"],8,380,36,32,10,
    ["2 fatias pão integral","1 lata atum","Iogurte grego","Alface, tomate"],
    ["Misture atum com iogurte","Monte o sanduíche com vegetais"]),
  r("o6","Arroz com frango pós-treino","🍚","postreino",["bulk"],20,560,42,68,10,
    ["100g arroz branco cozido","150g frango desfiado","Cenoura, ervilha","Cheiro-verde"],
    ["Refogue legumes em azeite","Adicione o frango e misture ao arroz","Tempere e finalize com cheiro-verde"]),
  r("o7","Iogurte grego com granola e mel","🍯","postreino",["maintain","cut"],5,340,28,36,8,
    ["200g iogurte grego 0%","30g granola","1 col. mel","Frutas vermelhas"],
    ["Monte em camadas no pote","Tome logo após o treino"]),
  r("o8","Barra caseira de proteína","🍫","postreino",["bulk","maintain"],30,380,24,42,14,
    ["2 scoops whey","80g aveia","60g pasta de amendoim","2 col. mel","30g cacau em pó"],
    ["Misture tudo até formar massa firme","Espalhe em forma forrada e leve ao freezer por 30 min","Corte em barras e mantenha refrigerado"]),

  /* ── SHAKES (10) ── */
  r("s1","Shake chocolate e amendoim","🍫","shake",["bulk"],3,420,32,38,16,
    ["1 scoop whey chocolate","250ml leite","1 banana","1 col. pasta de amendoim","Gelo"],
    ["Bata tudo no liquidificador","Sirva imediatamente"]),
  r("s2","Shake morango cheesecake","🍓","shake",["maintain"],3,310,28,28,8,
    ["1 scoop whey baunilha","200g iogurte grego","100g morangos frescos","Adoçante natural"],
    ["Bata até consistência cremosa","Sirva imediatamente ou gelado"],
    "Use morangos congelados para textura de sorvete."),
  r("s3","Shake verde antioxidante","🥦","shake",["cut"],4,260,26,18,6,
    ["1 scoop whey","Espinafre baby","½ abacaxi","Gengibre fresco","200ml água de coco"],
    ["Bata tudo até homogêneo","Sirva bem gelado com hortelã"]),
  r("s4","Shake banoffee proteico","🍌","shake",["bulk"],3,440,30,52,10,
    ["1 scoop whey baunilha","1 banana","250ml leite","1 tâmara","Canela em pó"],
    ["Bata todos os ingredientes","Polvilhe canela e sirva"]),
  r("s5","Shake café cremoso","☕","shake",["maintain"],4,300,28,18,12,
    ["1 scoop whey baunilha","1 dose café espresso gelado","200ml leite","Gelo"],
    ["Bata todos os ingredientes no liquidificador","Sirva em copo alto com canudo"]),
  r("s6","Shake tropical power","🏝️","shake",["cut","maintain"],4,290,26,32,4,
    ["1 scoop whey","100g manga","100g abacaxi","Hortelã fresca","Gelo"],
    ["Bata tudo com gelo abundante","Decore com hortelã"]),
  r("s7","Shake pré-treino high carb","⚡","shake",["bulk"],4,460,30,58,10,
    ["1 scoop whey","1 banana","30g aveia","1 col. mel","200ml leite"],
    ["Bata bem até incorporar a aveia","Tome 40 min antes do treino"]),
  r("s8","Shake low carb noturno","🌙","shake",["cut"],3,220,30,8,8,
    ["1 scoop caseína ou whey","200ml leite desnatado","Canela em pó"],
    ["Bata no shaker ou liquidificador","Tome antes de dormir"],
    "A caseína digere lentamente — perfeito para o anabolismo noturno."),
  r("s9","Shake matcha e pistache","🍵","shake",["maintain","cut"],4,280,24,22,10,
    ["1 scoop whey baunilha","1 col. chá matcha em pó","200ml leite de coco","30g pistache","Adoçante"],
    ["Bata tudo no liquidificador","Sirva com pistache picado por cima"]),
  r("s10","Shake red velvet proteico","❤️","shake",["bulk","maintain"],5,380,28,42,10,
    ["1 scoop whey baunilha","100g beterraba cozida","200ml leite","1 col. cacau","1 col. mel"],
    ["Bata tudo até cor uniforme e vibrante","Sirva imediatamente"]),
];

export const CATEGORY_CONFIG: Record<Recipe["category"], {
  label: string; emoji: string; thumbClass: string; badgeClass: string; shadow: string;
}> = {
  cafe:      { label: "Café da manhã", emoji: "☀️", thumbClass: "r-thumb-cafe",      badgeClass: "cat-cafe",      shadow: "var(--sh-cat-cafe)" },
  almoco:    { label: "Almoço",        emoji: "🌤️", thumbClass: "r-thumb-almoco",    badgeClass: "cat-almoco",    shadow: "var(--sh-cat-alm)"  },
  jantar:    { label: "Jantar",        emoji: "🌙", thumbClass: "r-thumb-jantar",    badgeClass: "cat-jantar",    shadow: "var(--sh-cat-jan)"  },
  lanche:    { label: "Lanche",        emoji: "🥗", thumbClass: "r-thumb-lanche",    badgeClass: "cat-lanche",    shadow: "var(--sh-cat-lan)"  },
  pretreino: { label: "Pré-treino",    emoji: "⚡", thumbClass: "r-thumb-pretreino", badgeClass: "cat-pretreino", shadow: "var(--sh-cat-pre)"  },
  postreino: { label: "Pós-treino",    emoji: "💪", thumbClass: "r-thumb-postreino", badgeClass: "cat-postreino", shadow: "var(--sh-cat-pos)"  },
  shake:     { label: "Shake",         emoji: "🥤", thumbClass: "r-thumb-shake",     badgeClass: "cat-shake",     shadow: "var(--sh-cat-sha)"  },
};

export const CATEGORY_LABEL: Record<Recipe["category"], string> = Object.fromEntries(
  Object.entries(CATEGORY_CONFIG).map(([k, v]) => [k, v.label])
) as Record<Recipe["category"], string>;
